
# do this in front of every test
default :
  image : immc/murphy-ci:v1.0
  before_script:
    - OMP_NUM_THREADS=1
    - "mkdir -p build"
    - "mkdir -p test/build"

# list of the stages
stages:
  - build
  - test
  - validation

# =============================================================================
build gcc:
  stage: build
  script:
    - "make destroy"
    - "ARCH_FILE=make_arch/make.docker_gcc_test make -j"

# =============================================================================
build test:
  stage: test
  artifacts: 
    paths: 
      - ./murphy_test
      - ./build/*.gcda
      - ./build/*.gcno
    when: on_success
  script:
    - "make destroy"
    - "ARCH_FILE=make_arch/make.docker_gcc_test make test -j"

# =============================================================================
compilation:
  stage: test
  dependencies:
    - build test
  script:
    - "mpirun -n 3 ./murphy_test --gtest_filter=test_* --gtest_output=\"xml:report_test.xml\" "
    - "gcovr -r . -e test "
  artifacts:
    reports:
      junit: report_test_*.xml

# =============================================================================
validation:
  stage: validation
  dependencies:
    - build test
  script:
    - "mpirun -n 3 ./murphy_test --gtest_filter=valid_* --gtest_output=\"xml:report_valid.xml\" "
    - "gcovr -r . -e test "
  artifacts:
    reports:
      junit: report_valid_*.xml