
# do this in front of every test
default :
  image : immc/murphy-ci:v1.0
  before_script:
    - OMP_NUM_THREADS=1
    - "mkdir build"
    - "mkdir test/build"

build:
  script:
    - "make destroy"
    - "ARCH_FILE=make_arch/make.docker_gcc_test make -j"

test:
  script:
    - "make destroy"
    - "ARCH_FILE=make_arch/make.docker_gcc_test make test -j"
    - "./murphy_test --gtest_filter=test_* --gtest_output="xml:report_test.xml" "
    - "gcovr -r . -e test "
  artifacts:
    paths:
      - report_test.xml
    reports:
      junit: report_test.xml

validation:
  script:
    - "make destroy"
    - "ARCH_FILE=make_arch/make.docker_gcc_test make test -j"
    - "./murphy_test --gtest_filter=valid_* --gtest_output="xml:report_valid.xml" "
    - "gcovr -r . -e test "
  artifacts:
    paths:
      - report_valid.xml
    reports:
      junit: report_valid.xml