name: murphy - CI

on: [push]

jobs:
  #----------------------------------------------------------------------------
  build-debug:
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 20
    container:
      image: vanreeslab/murphy:v1.4
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - run: mkdir build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make -j12
      # # save the exe created
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: murphy
      #     path: murphy

  # #----------------------------------------------------------------------------
  # build-test:
  #   #indicate to run on the beast using the correct docker
  #   runs-on: beast-tower
  #   timeout-minutes: 20
  #   container:
  #     image: vanreeslab/murphy:v1.4
  #   # define the steps
  #   steps:
  #     #checkout the repo
  #     - uses: actions/checkout@v2
  #     # do the build
  #     - run: mkdir build
  #     - run: mkdir test/build
  #     - name: build
  #       run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make test -j
  #     # # save the exe created
  #     # - uses: actions/upload-artifact@v2
  #     #   with:
  #     #     name: murphy_test
  #     #     path: murphy_test

  #----------------------------------------------------------------------------
  runtests_sequential_wavelet_2_2:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 20
    container:
      image: vanreeslab/murphy:v1.4
    # define the steps
    steps:
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: murphy_test
      # - name: fix permission
      #   run: chmod +x murphy_test
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - run: mkdir build
      - run: mkdir test/build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make test -j12 OPTS="-DWAVELET_N=2 -DWAVELET_NT=2 -DBLOCK_GS=2"
      # run the tests
      - name: build
        run: OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 1 ./murphy_test
  #----------------------------------------------------------------------------
  runtests_sequential_wavelet_4_0:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 20
    container:
      image: vanreeslab/murphy:v1.4
    # define the steps
    steps:
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: murphy_test
      # - name: fix permission
      #   run: chmod +x murphy_test
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - run: mkdir build
      - run: mkdir test/build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make test -j12 OPTS="-DWAVELET_N=4 -DWAVELET_NT=0 -DBLOCK_GS=4"
      # run the tests
      - name: build
        run: OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 1 ./murphy_test

  #----------------------------------------------------------------------------
  runtests_sequential_wavelet_4_2:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 20
    container:
      image: vanreeslab/murphy:v1.4
    # define the steps
    steps:
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: murphy_test
      # - name: fix permission
      #   run: chmod +x murphy_test
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - run: mkdir build
      - run: mkdir test/build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make test -j12 OPTS="-DWAVELET_N=4 -DWAVELET_NT=2 -DBLOCK_GS=4"
      # run the tests
      - name: build
        run: OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 1 ./murphy_test

  #----------------------------------------------------------------------------
  # run-test-OpenMP:
  #   needs: build-test
  #   #indicate to run on the beast using the correct docker
  #   runs-on: beast-tower
  #   timeout-minutes: 20
  #   container:
  #     image: vanreeslab/murphy:v1.4
  #   # define the steps
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: murphy_test
  #     - name: fix permission
  #       run: chmod +x murphy_test
  #     # do the build
  #     - name: build
  #       run: OMP_NUM_THREADS=5 mpirun --allow-run-as-root -n 1 ./murphy_test
  
  # #----------------------------------------------------------------------------
  # run-test-MPI:
  #   needs: build-test
  #   #indicate to run on the beast using the correct docker
  #   runs-on: beast-tower
  #   timeout-minutes: 20
  #   container:
  #     image: vanreeslab/murphy:v1.4
  #   # define the steps
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: murphy_test
  #     - name: fix permission
  #       run: chmod +x murphy_test
  #     # do the build
  #     - name: build
  #       run: OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 5 ./murphy_test
  
  # #----------------------------------------------------------------------------
  # run-test-Hybrid:
  #   needs: build-test
  #   #indicate to run on the beast using the correct docker
  #   runs-on: beast-tower
  #   timeout-minutes: 20
  #   container:
  #     image: vanreeslab/murphy:v1.4
  #   # define the steps
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: murphy_test
  #     - name: fix permission
  #       run: chmod +x murphy_test
  #     # do the build
  #     - name: build
  #       run: OMP_NUM_THREADS=5 mpirun --allow-run-as-root -n 5 ./murphy_test