name: murphy - CI

on: [push]

jobs:
  #----------------------------------------------------------------------------
  build-debug:
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 20
    container:
      image: vanreeslab/murphy:v1.5
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - run: mkdir build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make -j12

  #----------------------------------------------------------------------------
  runtests_wavelet_2_2:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 20
    container:
      image: vanreeslab/murphy:v1.5
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - run: mkdir build
      - run: mkdir test/build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make test -j12 OPTS="-DWAVELET_N=2 -DWAVELET_NT=2 -DBLOCK_GS=2"
      # run the tests
      - name: run_sequential
        run: OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 1 ./murphy_test
      # run the tests
      - name: run_mpi
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 3 ./murphy_test

  #----------------------------------------------------------------------------
  runtests_wavelet_4_0:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 20
    container:
      image: vanreeslab/murphy:v1.5
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - run: mkdir build
      - run: mkdir test/build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make test -j12 OPTS="-DWAVELET_N=4 -DWAVELET_NT=0 -DBLOCK_GS=4"
      # run the tests
      - name: run_sequential
        run: OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 1 ./murphy_test
      # run the tests
      - name: run_mpi
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 3 ./murphy_test

  #----------------------------------------------------------------------------
  runtests_wavelet_4_2:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 20
    container:
      image: vanreeslab/murphy:v1.5
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - run: mkdir build
      - run: mkdir test/build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test_ci make test -j12 OPTS="-DWAVELET_N=4 -DWAVELET_NT=2 -DBLOCK_GS=4"
      # run the tests
      - name: run_sequential
        run: OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 1 ./murphy_test
      # run the tests
      - name: run_mpi
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 3 ./murphy_test