name: validation

on: [pull_request]

jobs:
  #----------------------------------------------------------------------------
  runtests_wavelet_2_0:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 180
    container:
      image: vanreeslab/murphy-ci:v1.10
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test make test -j OPTS="-DWAVELET_N=2 -DWAVELET_NT=0 -DBLOCK_GS=2"
      # run the tests
      - name: run_mpi
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 7 ./murphy_test

  #----------------------------------------------------------------------------
  runtests_wavelet_2_2:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 180
    container:
      image: vanreeslab/murphy-ci:v1.10
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test make test -j OPTS="-DWAVELET_N=2 -DWAVELET_NT=2 -DBLOCK_GS=4"
      # run the tests
      - name: run_mpi
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 7 ./murphy_test

  #----------------------------------------------------------------------------
  runtests_wavelet_4_0:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 180
    container:
      image: vanreeslab/murphy-ci:v1.10
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test make test -j OPTS="-DWAVELET_N=4 -DWAVELET_NT=0 -DBLOCK_GS=6"
      # run the tests
      - name: run_mpi_high
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 7 ./murphy_test

  #----------------------------------------------------------------------------
  runtests_wavelet_4_2:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 180
    container:
      image: vanreeslab/murphy-ci:v1.10
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test make test -j OPTS="-DWAVELET_N=4 -DWAVELET_NT=2 -DBLOCK_GS=8"
      # run the tests
      - name: run_mpi_high
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 7 ./murphy_test

  #----------------------------------------------------------------------------
  runtests_wavelet_6_0:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 180
    container:
      image: vanreeslab/murphy-ci:v1.10
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test make test -j OPTS="-DWAVELET_N=6 -DWAVELET_NT=0 -DBLOCK_GS=10"
      # run the tests
      - name: run_mpi_high
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 7 ./murphy_test

  #----------------------------------------------------------------------------
  runtests_wavelet_6_2:
    # needs: build-test
    #indicate to run on the beast using the correct docker
    runs-on: beast-tower
    timeout-minutes: 180
    container:
      image: vanreeslab/murphy-ci:v1.10
    # define the steps
    steps:
      #checkout the repo
      - uses: actions/checkout@v2
      # do the build
      - name: build
        run: ARCH_FILE=make_arch/make.docker_gcc_test make test -j OPTS="-DWAVELET_N=6 -DWAVELET_NT=2 -DBLOCK_GS=12"
      # run the tests
      - name: run_mpi_high
        run: OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=1 mpirun --allow-run-as-root -n 7 ./murphy_test